version: "3.3"

# https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
# https://www.howtogeek.com/devops/how-to-simplify-docker-compose-files-with-yaml-anchors-and-extensions/
x-common: &common
    image: ${DOCKER_IMAGE_NAME:-schedulit-backend-django-image}
    build: .
    pull_policy: never
    environment:
      - DATABASE_URL
      - ENVIRONMENT
      - SECRET_KEY
      - DEBUG=${DEBUG:-false}
      - REDIS_HOST
      - REDIS_PORT
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      pipenv_check:
        condition: service_completed_successfully

services:
  backend_django:
    <<: *common
    container_name: backend-django-container
    command: gunicorn --bind 0.0.0.0:8080 schedulit.wsgi:application --workers=4
    depends_on:
      migration:
        condition: service_completed_successfully
      collectstatic:
        condition: service_completed_successfully
    restart: "on-failure"
    expose:  # this is only for internal use, so nginx can see it
      - 8080
    networks:
      - app-network
  migration:
    <<: *common
    command: python manage.py migrate --noinput
  collectstatic:
    <<: *common
    command: python manage.py collectstatic --noinput
  pipenv_check:
    <<: *common
    depends_on: []
    command: pipenv verify

  frontend:
    environment:
      - VITE_API_URL
      - VITE_API_URL_DJANGO
      - VITE_API_URL_RAILS
    command: npm run build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_volume:/app/dist/
    networks:
      - app-network

  backend_rails:
    environment:
      - DATABASE_URL
      - SECRET_KEY
    build:
      context: ./backend-ror
      dockerfile: Dockerfile

    command: ./bin/rails server -p 3000
    expose:  # this is only for internal use, so nginx can see it
      - 3000
    networks:
      - app-network

  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - frontend_volume:/frontend
    ports:
      - ${PORT_DJANGO:-8000}:8000
      - ${PORT_FRONTEND:-8001}:8001
      - ${PORT_RAILS:-8002}:8002
    depends_on:
      frontend:
        condition: service_completed_successfully
      backend_django:
        condition: service_started
      backend_rails:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    name: app-network

volumes:
  media_volume:
  static_volume:
  frontend_volume:
