# Generated by Django 5.0.4 on 2024-04-03 19:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_employee_id',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email', violation_error_message='user with this email address already exists.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(models.F('employee_id'), condition=models.Q(('employee_id__gt', '')), name='unique_employee_id', violation_error_message='Employee ID already in use.'),
        ),
    ]
