# Generated by Django 5.0.4 on 2024-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_unique_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Name'),
        ),
    ]
