# Generated by Django 5.0.3 on 2024-04-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='created', max_length=9, verbose_name='Status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'default_related_name': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='ShiftNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shift.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
